Repository cycle/schema-builder, pull requests merged in 2021-11, with the labels that each got.

#37 Fixes problem with getting typecast handler from defaults
  src/Compiler.php
  tests/Schema/Generator/TableGeneratorTest.php
Labels: bug

#38 Adds STI/JTI support
  composer.json
  src/Compiler.php
  src/Definition/Entity.php
  src/Definition/Field.php
  src/Definition/Inheritance.php
  src/Definition/Inheritance/JoinedTable.php
  src/Definition/Inheritance/SingleTable.php
  src/Exception/TableInheritance/DiscriminatorColumnNotPresentException.php
  src/Exception/TableInheritance/WrongDiscriminatorColumnException.php
  src/Exception/TableInheritance/WrongParentKeyColumnException.php
  src/Exception/TableInheritanceException.php
  src/Registry.php
  src/Relation/Traits/FieldTrait.php
  src/Relation/Traits/MorphTrait.php
  tests/Schema/CompilerTest.php
  tests/Schema/Definition/Inheritance/JoinedTableInheritanceTest.php
  tests/Schema/Definition/Inheritance/SingleTableInheritanceTest.php
  tests/Schema/EntityTest.php
  tests/Schema/Exception/TableInheritance/DiscriminatorColumnNotPresentExceptionTest.php
  tests/Schema/Exception/TableInheritance/WrongDiscriminatorColumnExceptionTest.php
  tests/Schema/Exception/TableInheritance/WrongParentKeyColumnExceptionTest.php
  tests/Schema/FieldsTest.php
  tests/Schema/Fixtures/BrokenSchemaModifier.php
  tests/Schema/Generator/GenerateModifiersTest.php
  tests/Schema/Generator/RenderModifiersTest.php
  tests/Schema/RegistryTest.php
Labels: enhancement

#39 Fix schema compute for STI children
  src/Compiler.php
  tests/Schema/Definition/Inheritance/SingleTableInheritanceTest.php
Labels: bug, enhancement
